name: CI/CD Pipeline

on:
  push:
    branches: [ staging ]

jobs:

  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging"
          destination_branch: "main"
          github_token: ${{ secrets.TOKEN }}
          pr_title: "Automated PR: Merging staging into main"
          pr_body: "This is an automated pull request to merge changes from the staging branch into the main branch."