name: CI/CD Pipeline

on:
  push:
    branches: [ staging ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Installed package list
      run: apt list --installed
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python -m unittest src/app/test_data_collection.py src/app/test_data_loading.py
    - name: Run integration tests
      run: |
        python -m unittest src/app/test_app.py
    - name: Run end-to-end test
      run: |
        python -m unittest src/app/test_end_to_end.py

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-workout:latest

  merge-to-main:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Merge staging branch into main
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff staging
          git push origin main